spring:
  application:
    name: url-shortener-command-service

  mvc:
    servlet:
      path: /api

  datasource:
    url: ${DATABASE_BASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: flyway
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
